# Generated by Django 4.0.4 on 2022-04-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BancoHubsoftModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('ip', models.CharField(max_length=100, unique=True, verbose_name='Host')),
                ('porta', models.CharField(max_length=100, verbose_name='Porta')),
                ('usuario', models.CharField(max_length=100, verbose_name='Usuario')),
                ('senha', models.CharField(max_length=100, verbose_name='Senha')),
                ('base', models.CharField(max_length=100, verbose_name='Base')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Banco Hubsoft',
                'verbose_name_plural': 'Banco Hubsoft',
                'managed': True,
            },
        ),
    ]
