# Generated by Django 4.0.4 on 2022-04-13 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SistemaOltModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('ip', models.CharField(max_length=100, unique=True, verbose_name='Host')),
                ('porta', models.CharField(max_length=100, verbose_name='Porta')),
                ('usuario', models.CharField(max_length=100, verbose_name='Usuario')),
                ('senha', models.CharField(max_length=100, verbose_name='Senha')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Sistema Olt',
                'verbose_name_plural': 'Sistema Olt',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SMNPOltModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.CharField(max_length=100, verbose_name='Community')),
                ('version', models.CharField(max_length=100, verbose_name='Version')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'SMNP Olt',
                'verbose_name_plural': 'SMNP Olt',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SistemaSlotModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField(default=0, verbose_name='SLOT')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('olt', models.ManyToManyField(to='olt.sistemaoltmodels')),
            ],
            options={
                'verbose_name': 'Sistema Slot',
                'verbose_name_plural': 'Sistema Slot',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SistemaPonModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pon', models.IntegerField(default=0, verbose_name='PON')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('slot', models.ManyToManyField(to='olt.sistemaslotmodels')),
            ],
            options={
                'verbose_name': 'Sistema Pon',
                'verbose_name_plural': 'Sistema Pon',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SistemaOnuModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onu', models.IntegerField(default=0, verbose_name='ONU')),
                ('codigo', models.CharField(max_length=100, unique=True, verbose_name='Codigo')),
                ('fhtt', models.CharField(max_length=100, verbose_name='FHTT')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descricao')),
                ('sinal', models.CharField(max_length=100, verbose_name='Sinal')),
                ('status', models.CharField(max_length=100, verbose_name='Status')),
                ('cliente', models.CharField(max_length=100, verbose_name='Cliente')),
                ('contrato', models.CharField(max_length=100, verbose_name='Contrato')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('pon', models.ManyToManyField(to='olt.sistemaponmodels')),
            ],
            options={
                'verbose_name': 'Sistema Onu',
                'verbose_name_plural': 'Sistema Onu',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='sistemaoltmodels',
            name='smnp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='olt.smnpoltmodels'),
        ),
    ]
