# Generated by Django 4.0.4 on 2022-04-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemaonumodels',
            name='vlan',
            field=models.IntegerField(default=0, verbose_name='Vlan'),
        ),
    ]
